name: example
description: Example app for the Uno editor

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uno_data:
    git:
      url: https://github.com/erickzanardo/uno.git
      path: packages/uno_data
  uno_top_view_game:
    path: ../packages/uno_top_view_game
  flame: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/levels/
