name: uno
description: The single screen level maker.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  equatable: ^2.0.5
  file_selector: ^1.0.0
  flame: ^1.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  nes_ui:
    git:
      url: https://github.com/erickzanardo/nes_ui.git
  path: ^1.8.3
  retro_game_controller:
    git:
      url: git@github.com:erickzanardo/retro_game_controller.git
  spritexp: ^0.1.0
  uno_data:
    path: packages/uno_data

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


flutter_launcher_icons:
  image_path: icon.png
  # android: launcher_icon
  # ios: true
  #min_sdk_android: 21
  #windows:
  #  generate: true
  #  image_path: "path/to/image.png"
  #  icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: icon.png
