name: uno_data
description: Contains the models for the Uno Level Editor
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.24.6
  very_good_analysis: ^5.0.0
